export type Sentence = {
  text: string
  grammar?: string
}

export type Category = {
  id: string
  name: string
  icon: string
  sentences: Sentence[]
}

export const CATEGORIES: Category[] = [
  {
    id: 'conditionals',
    name: 'Conditionals',
    icon: '⚡',
    sentences: [
      { text: 'Had the government invested more in infrastructure, the transport crisis would have been averted.', grammar: 'Type 3 inverted conditional — "Had" replaces "If...had"; formal academic register' },
      { text: 'Were she to apply for the position, she would undoubtedly be selected.', grammar: 'Type 2 inverted conditional — "Were...to" replaces "If she were to"' },
      { text: 'Should the data prove inconclusive, the researchers would need to conduct further trials.', grammar: 'Inverted "Should" conditional — expresses a realistic future possibility' },
      { text: 'Had it not been for the intervention of international organisations, the conflict might have escalated.', grammar: '"Had it not been for" — Type 3 counterfactual expressing a prevented outcome' },
      { text: 'Were prices to fall significantly, consumer spending would inevitably rise.', grammar: '"Were...to" structure — formal hypothetical future, suitable for academic prose' },
      { text: 'Should the temperature continue to increase, coastal communities would face severe flooding.', grammar: '"Should" inversion — commonly used in policy documents and academic reports' },
      { text: 'Had the authorities acted sooner, the environmental damage could have been minimised.', grammar: 'Type 3 with modal "could have been" — expresses unrealised past possibility' },
      { text: 'Were the company to relocate, hundreds of jobs would be lost.', grammar: '"Were...to" — indicates a hypothetical future scenario with serious consequences' },
      { text: 'Should more funding be allocated to renewable energy, the transition from fossil fuels would accelerate.', grammar: 'Passive + inverted conditional — "should...be allocated" in formal writing' },
      { text: 'Had stricter regulations been in place, the financial collapse might have been prevented.', grammar: 'Type 3 passive — "had...been in place" + modal perfect passive in result clause' },
    ],
  },
  {
    id: 'passive',
    name: 'Passive Voice',
    icon: '🔄',
    sentences: [
      { text: 'The legislation is expected to have been drafted by the end of the financial year.', grammar: 'Complex passive — "is expected to have been" combines present + perfect infinitive passive' },
      { text: 'Significant progress has been made in reducing carbon emissions over the past decade.', grammar: 'Present perfect passive — focuses on result; agent omitted as unimportant' },
      { text: 'The report is believed to have been submitted without the required supporting evidence.', grammar: '"is believed to have been" — reporting verb passive with perfect infinitive' },
      { text: 'Several recommendations were put forward by the committee but were subsequently rejected.', grammar: 'Double passive in one sentence — two passive verbs linked by "but"' },
      { text: 'The data collected over three decades has been used to formulate the new policy.', grammar: 'Reduced relative clause — "data collected" = "data that was collected"; present perfect passive main verb' },
      { text: 'The building is said to have been designed by one of the leading architects of the era.', grammar: '"is said to have been designed" — reporting passive + perfect infinitive passive' },
      { text: 'More than a thousand species are thought to be threatened by habitat destruction each year.', grammar: '"are thought to be" — present passive with simple infinitive' },
      { text: 'The agreement is understood to have been reached after months of difficult negotiations.', grammar: '"is understood to have been reached" — complex passive reporting structure' },
      { text: 'Considerable resources have been devoted to understanding the long-term effects of urbanisation.', grammar: '"have been devoted to" + gerund — present perfect passive with prepositional complement' },
      { text: 'The findings are expected to be published in a peer-reviewed journal later this year.', grammar: '"are expected to be published" — future event expressed via passive reporting verb' },
    ],
  },
  {
    id: 'inversion',
    name: 'Inversion',
    icon: '↩️',
    sentences: [
      { text: 'Not only did the government fail to address the issue, but it also introduced counterproductive measures.', grammar: '"Not only...but also" — auxiliary "did" inverted before subject for emphasis' },
      { text: 'Rarely has such a significant shift in public opinion been observed in so short a time.', grammar: '"Rarely" inversion — present perfect auxiliary "has" placed before subject' },
      { text: 'Under no circumstances should personal data be shared without the explicit consent of the individual.', grammar: '"Under no circumstances" — negative adverbial triggers inversion of "should" before subject' },
      { text: 'No sooner had the legislation been passed than it was challenged in the courts.', grammar: '"No sooner...than" — past perfect inverted after opening negative adverbial' },
      { text: 'Only when the scale of the problem became apparent did officials take decisive action.', grammar: '"Only when" inversion — auxiliary "did" fronted in main clause after adverbial clause' },
      { text: 'Never before has the rate of technological change posed such a profound challenge to society.', grammar: '"Never before" — present perfect inverted for maximum rhetorical emphasis' },
      { text: 'Seldom do economic growth and environmental protection advance simultaneously.', grammar: '"Seldom" inversion — auxiliary "do" fronted with compound subject following' },
      { text: 'Not until the final results were announced did investors regain confidence in the market.', grammar: '"Not until" inversion — emphasis on the delayed moment of change' },
      { text: 'So rapidly has the technology developed that regulators have struggled to keep pace.', grammar: '"So + adverb" inversion — "so rapidly has" triggers subject-auxiliary inversion + result clause' },
      { text: 'Little did the researchers anticipate that their findings would generate such widespread controversy.', grammar: '"Little" inversion — "little did...anticipate" stresses the unexpectedness of the outcome' },
    ],
  },
  {
    id: 'reported',
    name: 'Reported Speech',
    icon: '💬',
    sentences: [
      { text: 'The minister announced that the proposed reforms would be implemented in stages over the following year.', grammar: 'Backshift: "will" → "would"; "next" → "the following" — standard reported speech shifts' },
      { text: 'Scientists warned that unless immediate action was taken, the damage would prove irreversible.', grammar: 'Reported conditional — "is taken" → "was taken"; "will prove" → "would prove"' },
      { text: 'The spokesperson confirmed that the investigation had been ongoing for several months.', grammar: 'Backshift to past perfect — "has been" → "had been" in reported speech' },
      { text: 'Analysts predicted that the economic recovery would take longer than had initially been anticipated.', grammar: 'Embedded past perfect passive in reported prediction — "had...been anticipated"' },
      { text: 'The committee acknowledged that insufficient attention had been paid to the needs of rural communities.', grammar: 'Reported acknowledgement with past perfect passive — formal academic register' },
      { text: 'Critics argued that the policy had been poorly designed and was unlikely to achieve its stated objectives.', grammar: 'Two backshifted clauses — "has been designed" → "had been designed"; "is" → "was"' },
      { text: 'Researchers suggested that the findings should be interpreted with considerable caution.', grammar: '"Should" does not backshift — modal suggestion is retained unchanged in reported speech' },
      { text: 'The report concluded that further investment would be required if the targets were to be met.', grammar: 'Reported conclusion with embedded formal conditional — "were to be met"' },
      { text: 'Officials stated that the negotiations had reached a critical stage and that a breakthrough was imminent.', grammar: 'Two parallel "that" clauses — same reporting verb governs both subordinate clauses' },
      { text: 'Experts cautioned that the technology, while promising, had yet to be tested at scale.', grammar: '"Had yet to be tested" — past perfect passive expressing an unfulfilled requirement' },
    ],
  },
  {
    id: 'cleft',
    name: 'Cleft Sentences',
    icon: '✂️',
    sentences: [
      { text: 'It is the lack of affordable housing that has driven many young people out of the city.', grammar: '"It is...that" cleft — focuses emphasis on "the lack of affordable housing" as the key cause' },
      { text: 'What the data clearly demonstrates is that inequality has widened significantly over the past two decades.', grammar: '"What...is" pseudo-cleft — noun clause subject + "is" + that-clause predicate' },
      { text: 'It was not until the industrial revolution that the pace of urbanisation began to accelerate dramatically.', grammar: '"It was not until...that" cleft — emphasises the turning point in time' },
      { text: 'What the government has failed to recognise is the long-term cost of underinvesting in education.', grammar: '"What...is" pseudo-cleft — moves focus to the government\'s critical oversight' },
      { text: 'It is through international cooperation that the most pressing environmental challenges can be addressed.', grammar: '"It is...that" cleft with prepositional phrase — emphasises the means or method' },
      { text: 'What distinguishes this approach from previous attempts is its emphasis on community-led solutions.', grammar: '"What...is" cleft — subject is a "what" clause; predicate is a noun phrase' },
      { text: 'It is the wealthiest nations that bear the greatest responsibility for reducing carbon emissions.', grammar: '"It is...that" cleft — redirects focus to the agent bearing primary responsibility' },
      { text: 'What the research consistently shows is that early intervention yields the most significant long-term benefits.', grammar: '"What...is that" cleft — links a generalised finding to a specific conclusion' },
      { text: 'It was only after considerable public pressure that the authorities agreed to review the decision.', grammar: '"It was only...that" cleft — "only" adds restrictive emphasis to the triggering condition' },
      { text: 'What makes this period particularly significant is the unprecedented convergence of social and economic disruption.', grammar: '"What...is" cleft — "what makes" clause as subject + noun phrase as predicate' },
    ],
  },
]

export const TASK1_CATEGORIES: Category[] = [
  {
    id: 'line-graphs',
    name: 'Line Graphs',
    icon: '📈',
    sentences: [
      { text: 'The line graph illustrates the changes in energy consumption across five countries between 1990 and 2020.', grammar: 'Standard opening — "illustrates the changes in [topic] across [subjects] between [years]"' },
      { text: 'Overall, it is evident that oil usage experienced a dramatic surge, while renewable energy climbed steadily throughout the period.', grammar: 'Overview sentence — contrasts two trends using "while"; "dramatic surge" vs "climbed steadily"' },
      { text: 'France consistently outperformed Germany throughout the period, with the gap widening particularly after 2005.', grammar: '"consistently outperformed...throughout the period" — adverb + verb collocation for sustained comparison' },
      { text: 'Having peaked at 45 million in 2010, the figure subsequently plummeted to just 28 million by the end of the period.', grammar: 'Participle clause — "having peaked at" introduces a past high point before describing a decline' },
      { text: 'The proportion of users accessing the internet via mobile devices rose exponentially from 2008 onwards.', grammar: '"rose exponentially from [year] onwards" — strong upward trend with a clear starting point' },
      { text: 'Both categories fluctuated considerably during the early years before levelling off at approximately 30% in 2015.', grammar: '"fluctuated considerably...before levelling off at" — two-phase trend in one sentence' },
      { text: 'By far the most striking feature is the sharp decline in coal consumption, which nearly halved over the two-decade period.', grammar: '"By far the most striking feature is" — strong superlative opener for highlighting a key trend' },
      { text: 'The figures for urban and rural populations converged significantly, reaching an almost identical level by 2018.', grammar: '"converged significantly" — useful for describing two lines approaching each other' },
      { text: 'After remaining stable throughout most of the 1990s, sales began to climb steadily from 2001 onwards.', grammar: 'Adverbial opener — "After [verb+ing]" introduces a stable period before a change begins' },
      { text: 'In contrast to the UK, where usage dropped significantly, Germany witnessed a sharp increase over the same period.', grammar: '"In contrast to [X], where [change], [Y] witnessed" — embedded relative clause for direct contrast' },
    ],
  },
  {
    id: 'bar-charts',
    name: 'Bar Charts',
    icon: '📊',
    sentences: [
      { text: 'The bar chart compares the proportion of household income spent on food and leisure across six European countries in 2019.', grammar: 'Standard opening — "compares [what is measured] across [categories] in [year]"' },
      { text: 'Overall, the United Kingdom recorded the highest figure by a considerable margin, while Poland showed the lowest across all categories.', grammar: 'Overview — "by a considerable margin" strengthens the superlative; "across all categories" generalises the finding' },
      { text: 'At 45%, transport costs in Japan significantly outstripped those in all other countries surveyed.', grammar: '"outstripped those in all other countries surveyed" — strong comparison collocation; figure leads the sentence' },
      { text: 'Healthcare spending in the United States dwarfed all other categories, standing at approximately three times the global average.', grammar: '"dwarfed all other categories" — vivid verb for dominance; "standing at" introduces the supporting figure' },
      { text: 'While the figures for Germany and France exhibit a marginal difference, both countries considerably outpace their eastern European counterparts.', grammar: '"exhibit a marginal difference" — for near-equal bars; "outpace their counterparts" for group comparison' },
      { text: 'The proportion allocated to education ranked highest in South Korea, accounting for the largest share at nearly 18%.', grammar: '"ranked highest in [country], accounting for the largest share at [figure]" — two-part description of a top bar' },
      { text: 'There is a stark contrast between developed and developing nations, with the former spending nearly double the latter on infrastructure.', grammar: '"stark contrast...with the former...the latter" — formal comparison using "former/latter" avoids repetition' },
      { text: 'With the exception of Japan, all countries surveyed showed a broadly similar pattern of expenditure across the five categories.', grammar: '"With the exception of [X], all [subjects] showed a broadly similar pattern" — generalisation with one outlier' },
      { text: 'Technology exports from China more than doubled between 2010 and 2020, causing it to overtake the United States for the first time.', grammar: '"more than doubled...causing it to overtake" — cause-and-effect structure linking a trend to its consequence' },
      { text: 'The gap between the highest and lowest performing nations was particularly pronounced in the healthcare and education sectors.', grammar: '"the gap...was particularly pronounced in" — highlights where a disparity is most significant' },
    ],
  },
  {
    id: 'pie-charts',
    name: 'Pie Charts',
    icon: '🥧',
    sentences: [
      { text: 'The pie charts illustrate the breakdown of household energy consumption in Germany in 1990 and 2020.', grammar: 'Standard opening — "illustrate the breakdown of [topic] in [place] in [years]"' },
      { text: 'Overall, heating accounted for the largest proportion in both years, while electricity constituted the smallest share.', grammar: 'Overview — "accounted for the largest proportion" vs "constituted the smallest share" for two extremes' },
      { text: 'Transport claimed the lion\'s share of government expenditure, accounting for well over a third of the total budget.', grammar: '"claimed the lion\'s share" — idiomatic phrase for dominant category; "well over a third" avoids exact figures' },
      { text: 'Food and clothing collectively accounted for approximately two-fifths of total household spending in the base year.', grammar: '"collectively accounted for approximately two-fifths" — groups categories together using a fraction' },
      { text: 'At a mere 4%, expenditure on culture and recreation remained only a fraction of that spent on housing.', grammar: '"At a mere [%]" — "mere" emphasises smallness; "only a fraction of" compares proportionally' },
      { text: 'The distribution is heavily skewed towards service industries, which jointly represented over 60% of the national economy.', grammar: '"heavily skewed towards" — strong descriptor for uneven distribution; "jointly represented" groups subcategories' },
      { text: 'Manufacturing and agriculture, comprising approximately 15% and 8% respectively, saw their combined share decline sharply by 2020.', grammar: '"comprising [X]% and [Y]% respectively" — precise multi-item description using a single relative clause' },
      { text: 'The share attributed to renewable energy was more than double that recorded a decade earlier, rising from 12% to 25%.', grammar: '"more than double that recorded" — elegant comparative without repeating the noun; "rising from X to Y" adds precision' },
      { text: 'With the notable exception of Asia, all other regions showed a broadly comparable distribution of trade activity.', grammar: '"With the notable exception of" — stronger than "except for"; signals an outlier before a generalisation' },
      { text: 'Spending on defence, at approximately one-fifth of the total, considerably outweighed investment in social welfare programmes.', grammar: 'Parenthetical figure — ", at approximately one-fifth," embedded mid-sentence for fluency' },
    ],
  },
  {
    id: 'maps',
    name: 'Maps',
    icon: '🗺️',
    sentences: [
      { text: 'The maps illustrate how the coastal town of Bradfield has transformed over a fifty-year period from 1970 to 2020.', grammar: 'Standard opening — "illustrate how [place] has transformed over [period] from [year] to [year]"' },
      { text: 'Overall, the area underwent substantial development, with the farmland to the north being replaced by a residential zone.', grammar: 'Overview — "underwent substantial development" is the main claim; "with [noun] being replaced" adds supporting detail' },
      { text: 'The factory situated in the northern corner was demolished and replaced by a modern shopping centre.', grammar: '"situated in the [direction] corner was demolished and replaced by" — location + transformation in one sentence' },
      { text: 'A dual carriageway running through the centre of town was constructed, significantly improving connectivity across the region.', grammar: 'Participial phrase — "running through" locates the road; "significantly improving" shows the result' },
      { text: 'The woodland adjacent to the river was removed to make way for a new leisure complex and car park.', grammar: '"adjacent to [feature] was removed to make way for" — reason clause explains the demolition' },
      { text: 'The school building, originally located opposite the town hall, was extended considerably during the later period.', grammar: 'Embedded clause — ", originally located opposite [landmark]," gives prior position before describing the change' },
      { text: 'Several residential properties on both sides of the main road were converted into commercial premises between 1990 and 2020.', grammar: '"on both sides of" — useful spatial phrase; "converted into" for change of use rather than demolition' },
      { text: 'The harbour, which had previously remained unchanged since its construction, was expanded and upgraded during the later period.', grammar: '"which had previously remained unchanged since its construction" — relative clause contrasts past stability with present change' },
      { text: 'A pedestrian walkway was developed along the northern bank, connecting the old town to the newly built cultural centre.', grammar: '"developed along the [direction] bank, connecting" — location + participial result clause' },
      { text: 'The industrial zone to the east of the railway line was relocated and transformed into a public park and recreation area.', grammar: '"to the east of the railway line was relocated and transformed into" — compass direction + double transformation verb' },
    ],
  },
  {
    id: 'process-diagrams',
    name: 'Process Diagrams',
    icon: '⚙️',
    sentences: [
      { text: 'The diagram illustrates the process by which raw coffee beans are transformed into the finished product ready for retail sale.', grammar: 'Standard opening — "illustrates the process by which [input] is transformed into [output]"' },
      { text: 'Overall, the process comprises seven distinct stages, commencing with the harvesting of ripe berries and culminating in packaging.', grammar: 'Overview — "comprises [N] distinct stages, commencing with...and culminating in" covers start to finish in one sentence' },
      { text: 'Once the outer casing has been removed, the beans are subjected to a thorough washing process to eliminate impurities.', grammar: '"Once [present perfect passive], [subject] is subjected to" — temporal clause + complex passive for sequential steps' },
      { text: 'In the penultimate stage, the dried beans undergo roasting at temperatures exceeding 200 degrees, thereby altering their chemical composition.', grammar: '"In the penultimate stage...undergo...thereby [verb+ing]" — position marker + cause-and-effect ending' },
      { text: 'Prior to fermentation, the harvested grapes are passed through a mechanical press to extract the juice from the pulp.', grammar: '"Prior to [noun], [subject] is passed through" — formal temporal preposition for ordering steps' },
      { text: 'The mixture is then transferred to a series of heated chambers, where it is left to mature for a minimum of six weeks.', grammar: '"transferred to...where it is left to [verb] for" — movement + duration embedded in a relative clause' },
      { text: 'At this juncture, the material is meticulously inspected for defects before being passed on to the next stage of production.', grammar: '"At this juncture" — formal discourse marker; "meticulously inspected" raises register' },
      { text: 'The recycled material is converted into small pellets, which are subsequently melted and moulded into new plastic containers.', grammar: '"converted into...which are subsequently melted and moulded" — two-step chain using a relative clause' },
      { text: 'The water is first filtered to remove solid particles, then treated with chemicals to eliminate any remaining bacterial contamination.', grammar: '"first...then" — simplest sequencing pair; two parallel passive infinitive clauses' },
      { text: 'Once processing is complete, the final product is packaged, labelled, and dispatched to distribution centres across the country.', grammar: '"Once [noun] is complete, [subject] is [verb], [verb], and [verb]" — three-verb passive list for the final stage' },
    ],
  },
  {
    id: 'tables',
    name: 'Tables',
    icon: '📋',
    sentences: [
      { text: 'The table compares five countries across four socioeconomic indicators: GDP per capita, life expectancy, literacy rate, and unemployment.', grammar: 'Standard opening — "compares [N] [subjects] across [N] indicators:" followed by a colon-introduced list' },
      { text: 'Overall, Japan ranks highest in life expectancy and literacy, while Brazil records the lowest figures across most indicators.', grammar: 'Overview — two extremes named explicitly; "across most indicators" avoids overstating a universal claim' },
      { text: 'Norway consistently outperforms all other nations, with its GDP per capita standing at approximately twice the global average.', grammar: '"consistently outperforms all other nations" — strong superlative; "standing at approximately twice" adds a ratio' },
      { text: 'The figures for literacy rate range from a high of 99% in South Korea to a low of 61% in Nigeria.', grammar: '"range from a high of [X] in [place] to a low of [Y] in [place]" — standard formula for showing spread' },
      { text: 'There is a marked disparity between developed and developing nations, particularly in the areas of healthcare spending and educational attainment.', grammar: '"marked disparity between...particularly in the areas of" — general claim followed by specific sectors' },
      { text: 'With the exception of China, all Asian economies surveyed show a comparable level of export activity relative to GDP.', grammar: '"With the exception of [X], all [group] show a comparable level of [metric] relative to [benchmark]"' },
      { text: 'Germany presents a striking contrast to its European neighbours, recording both the highest trade surplus and the lowest unemployment rate.', grammar: '"presents a striking contrast...recording both the highest...and the lowest" — double superlative for emphasis' },
      { text: 'Life expectancy in the United States, at 78 years, lags considerably behind that of Japan, which stands at 84 years.', grammar: 'Parenthetical figure — ", at [N] years," mid-sentence; "lags considerably behind that of" for a precise comparison' },
      { text: 'The data reveals that countries with higher literacy rates consistently outperform those with lower rates in terms of economic productivity.', grammar: '"The data reveals that...consistently outperform those with lower rates in terms of" — analytical conclusion sentence' },
      { text: 'Australia stands out as a notable outlier, achieving high scores across all four categories despite its relatively small population.', grammar: '"stands out as a notable outlier, achieving...despite" — concessive clause highlights an unexpected result' },
    ],
  },
]
